1)SELECT NAME,CITY FROM EMPLOYEE_TABLE WHERE SALARY IN(SELECT MAX(SALARY) FROM EMPLOYEE_TABLE);

2)SELECT * FROM EMPLOYEE_TABLE WHERE EXPERIENCE >= 2 AND EXPERIENCE <=7;

3)SELECT MAX(AGE) FROM EMPLOYEE_TABLE WHERE AGE IN (SELECT AGE WHERE SALARY<4000);

4)SELECT AGE FROM EMPLOYEE_TABLE WHERE AGE IN (SELECT AVG(SALARY) FROM EMPLOYEE_TABLE);

5)SELECT * FROM employee_table WHERE EXPERIENCE IN (SELECT MAX(EXPERIENCE) FROM employee_table);

6)SELECT NAME FROM employee_table WHERE EXPERIENCE IN (SELECT MIN(EXPERIENCE)FROM employee_table WHERE DEPARTMENT='CSE');

7)

8)SELECT COUNT(NAME) FROM employee_table WHERE COUNTRY='GERMANY';

9)SELECT SUM(SALARY) AS 'SALARY' FROM EMPLOYEE_TABLE WHERE DEPARTMENT ='ETE';

10)SELECT MIN(NAME) AS 'MIN_NAME' FROM employee_table;










SELECT NAME, CITY FROM EMPLOYEE_TABLE WHERE SALARY IN (SELECT MAX(SALARY) FROM EMPLOYEE_TABLE);
SELECT * FROM EMPLOYEE_TABLE WHERE EXPERIENCE >=2 AND EXPERIENCE <=7;
SELECT MAX(AGE) FROM EMPLOYEE_TABLE WHERE AGE IN (SELECT AGE WHERE SALARY<4000);
SELECT AGE FROM EMPLOYEE_TABLE WHERE AGE IN (SELECT AVG(SALARY) FROM EMPLOYEE_TABLE);
SELECT * FROM EMPLOYEE_TABLE WHERE EXPERIENCE IN (SELECT MAX(EXPERIENCE) FROM EMPLOYEE_TABLE);
SELECT NAME FROM EMPLOYEE_TABLE WHERE EXPERIENCE IN (SELECT MIN(EXPERIENCE) FROM EMPLOYEE_TABLE WHERE DEPARTMENT IN('CSE'));
SELECT COUNTRY FROM EMPLOYEE_TABLE WHERE AGE IN ((SELECT MAX(AGE) FROM EMPLOYEE_TABLE WHERE DESIGNATION IN('AP')));
SELECT SUM(SALARY) AS 'SALARY_EXPENSE' FROM EMPLOYEE_TABLE WHERE DEPARTMENT = 'ETE';
SELECT MIN(NAME) AS 'MIN_NAME' FROM EMPLOYEE_TABLE;
